language: node_js
node_js:
  - 'stable'

env:
  - API_VERSION=v1

install: 
  - npm install

before_script:
  - ./cc-test-reporter before-build
  
script:
  - npm run test:coveralls
  - npm run test:coverage

cache:
  directories:
  - "$HOME/.npm"
