language: node_js
node_js:
  - 'stable'

env:
  - API_VERSION=v1

install: 
  - npm install -g mocha

services:
  - postgresql

before_script:
  - travis_wait 30 npm install
  - psql -c 'create database teamworkdb;' -U postgres
  - travis_wait npm install
  - node database/queriesdb.js createAllTables
  - travis_wait 30 node database/queriesdb.js insertAllData

script:
  - 'true'

after_success:
  - npm run coverage
  
cache:
  directories:
  - 'node_modules'
