language: node_js
node_js:
  - 'stable'

env:
  - API_VERSION=v1

install: 
  - npm install -g mocha

services:
  - postgresql

before_script:
  - travis_wait 30 npm install
  - psql -c 'create database teamworkdb;' -U postgres
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - 'true'

after_success:
  - npm run coverage
  - ./cc-test-reporter after-build --exit-code $Test reporter ID
  
cache:
  directories:
  - 'node_modules'
