language: node_js
node_js:
  - 'stable'

env:
  - API_VERSION=v1

install: 
  - npm install -g mocha

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - npm run build

script:
  - 'true'

after_success:
  - npm run coverage
  
cache:
  directories:
  - 'node_modules'
