language: node_js
node_js:
  - 'stable'

env:
  - API_VERSION=v1

install: 
  - npm install -g mocha

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - 'true'

after_success:
  - npm run coverage

addons:
  jwt:
     secure: <'RANDOM_TOKEN_IT_JUST_KEEPS_GOING' ENCRYPTED>
  
cache:
  directories:
  - 'node_modules'
