language: node_js
node_js:
  - 'stable'

env:
  - API_VERSION=v1

install: 
  - npm install

script:
  - $repo_token
  - npm run test

after_success:
  - npm run coveralls

cache:
  directories:
  - "$HOME/.npm"
