language: node_js
node_js:
  - 'stable'

env:
  - API_VERSION=v1

install: 
  - npm install

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - 'true'

after_script:
  - npm run coveralls
  - npm run coverage
  
cache:
  directories:
  - "$HOME/.npm"
