language: node_js
node_js:
  - 'stable'

env:
  - API_VERSION=v1

install: 
  - npm install

script:
  - 'true'

after_script:
  - npm run coveralls
  - npm run coverage

cache:
  directories:
  - "$HOME/.npm"
